# Global values
global:
  guid: ""  # Will be populated from .env

# AWS / S3 Configuration
aws:
  region: us-east-1
  credentials:
    accessKey: ""
    secretKey: ""
  baseDomain: ""
  bucket:
    name: "grafana-{{ .Values.global.guid }}"
    endpoint: "s3.amazonaws.com"

# Cluster Configuration
cluster:
  name: single-node-cluster
  namespace: open-cluster-management

# Network Configuration
network:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - 172.30.0.0/16
  machineNetwork:
    - cidr: 10.0.0.0/16

# Authentication
auth:
  pullSecret: ""
  sshPrivateKey: ""
  sshPublicKey: ""

# Tags
tags:
  owner: ""

