# Global values
global:
  guid: ""  # Will be populated from .env

# AWS / S3 Configuration
aws:
  region: "us-west-1"
  credentials:
    accessKey: ""
    secretKey: ""
  baseDomain: ""
  bucket:
    name: "grafana-{{ .Values.global.guid }}"
    endpoint: "s3.amazonaws.com"
    region: "us-east-2"

# ACM Configuration
acm:
  namespace: open-cluster-management

# Observability Configuration
observability:
  namespace: open-cluster-management-observability

# Cluster Configuration
cluster:
  name: single-node-cluster
  namespace: single-node-cluster
  image: 
    #quay.io/openshift-release-dev/ocp-release:4.18.4-multi
    name: img4.18.4-multi-appsub

# Network Configuration
network:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - 172.30.0.0/16
  machineNetwork:
    - cidr: 10.0.0.0/16

# Authentication
auth:
  pullSecret: ""
  sshPrivateKey: ""
  sshPublicKey: ""

# Tags
tags:
  owner: ""

