# Global values
global:
  guid: "" # Will be populated from .env

# AWS / S3 Configuration
aws:
  region: "us-west-1"
  credentials:
    accessKey: "" # Will be populated from .env
    secretKey: "" # Will be populated from .env
  baseDomain: "" # Will be populated from .env
  bucket:
    name: grafana-{{ .Values.global.guid }}" # Will be populated from .env
    endpoint: "s3.amazonaws.com"
    region: "us-east-2"

# ACM Configuration
acm:
  namespace: open-cluster-management

# Observability Configuration
observability:
  namespace: open-cluster-management-observability

# Cluster Configuration
cluster:
  name: single-node-cluster # Will be populated from .env
  namespace: single-node-cluster # Will be populated from .env
  image: 
    name: img4.18.4-multi-appsub #quay.io/openshift-release-dev/ocp-release:4.18.4-multi

# Network Configuration
network:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - 172.30.0.0/16
  machineNetwork:
    - cidr: 10.0.0.0/16

# Authentication
auth:
  pullSecret: "" # Will be populated from .env
  sshPrivateKey: "" # Will be populated from .env
  sshPublicKey: "" # Will be populated from .env

# Tags
tags:
  owner: "" # Will be populated from .env 

