apiVersion: v1
kind: Secret
metadata:
  name: multiclusterhub-operator-pull-secret
  namespace: {{ .Values.observability.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ get (lookup "v1" "Secret" "openshift-config" "pull-secret").data ".dockerconfigjson" }}

