apiVersion: v1
kind: Secret
metadata:
  name: multiclusterhub-operator-pull-secret
  namespace: open-cluster-management-observability
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: "{from-secret: open-cluster-management/multiclusterhub-operator-pull-secret}"

