apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: {{ .Values.aws.bucket.name }}
      access_key: {{ .Values.aws.credentials.accessKey }}
      secret_key: {{ .Values.aws.credentials.secretKey }}
      endpoint: {{ .Values.aws.bucket.endpoint }}
      region: {{ .Values.aws.region }}

