apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: aws-creds
  namespace: {{ .Values.acm.namespace }}
  labels:
    cluster.open-cluster-management.io/credentials: ""
    cluster.open-cluster-management.io/type: aws
stringData:
  aws_access_key_id: {{ .Values.aws.credentials.accessKey }}
  aws_secret_access_key: {{ .Values.aws.credentials.secretKey }}
  baseDomain: {{ .Values.aws.baseDomain }}
data:
  pullSecret: {{ .Values.auth.pullSecret }}
  ssh-privatekey: {{ .Values.auth.sshPrivateKey }}
  ssh-publickey: {{ .Values.auth.sshPublicKey }}
  # If you want to add them
  # httpProxy: ""
  # httpsProxy: ""
  # noProxy: ""
  # additionalTrustBundle: ""

