apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-cluster # EKS Cluster name
  region: us-east-2 # Region Code to place EKS Cluster
  version: "1.30"
managedNodeGroups:
- name: primary # Name of node group in EKS Cluster
  instanceType: t3.small # Instance type for node group
  desiredCapacity: 3 # Number of worker nodes- default is 2