apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: eks-cluster
  labels:
    name: eks-cluster
    cloud: auto-detect
    vendor: auto-detect
    cluster.open-cluster-management.io/clusterset: default
  annotations: {}
spec:
  hubAcceptsClient: true
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: eks-cluster
  namespace: eks-cluster
spec:
  clusterName: eks-cluster
  clusterNamespace: eks-cluster
  clusterLabels:
    name: eks-cluster
    cloud: auto-detect
    vendor: auto-detect
    cluster.open-cluster-management.io/clusterset: default
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
