apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cluster-aws-creds
  namespace: {{ .Values.cluster.namespace }}
stringData:
  aws_access_key_id: {{ .Values.aws.credentials.accessKey }}
  aws_secret_access_key: {{ .Values.aws.credentials.secretKey }}