apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: {{ .Values.cluster.namespace }}
stringData:
  aws_access_key_id: {{ .Values.aws.credentials.accessKey }}
  aws_secret_access_key: {{ .Values.aws.credentials.secretKey }}
  baseDomain: {{ .Values.aws.baseDomain }}
  pullSecret: {{ .Values.auth.pullSecret }}
  ssh-privatekey: {{ .Values.auth.sshPrivateKey }}
  ssh-publickey: {{ .Values.auth.sshPublicKey }}
type: Opaque

