apiVersion: v1
kind: Secret
metadata:
  name: cluster-ssh-private-key
  namespace: {{ .Values.cluster.namespace }}
type: Opaque
stringData:
#   ssh-privatekey: {{ .Values.auth.sshPrivateKey }}
    ssh-privatekey: # injected on create