apiVersion: v1
kind: Secret
metadata:
  name: cluster-pull-secret
  namespace: {{ .Values.cluster.namespace }}
type: Opaque
stringData:
  .dockerconfigjson: # injected on create
type: kubernetes.io/dockerconfigjson
# stringData:
#   pullSecret: {{ .Values.auth.pullSecret }}