apiVersion: v1
kind: Secret
metadata:
  name: cluster-pull-secret
  namespace: {{ .Values.cluster.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  {{- with (lookup "v1" "Secret" "openshift-config" "pull-secret") }}
  .dockerconfigjson: {{ get .data ".dockerconfigjson" }}
  {{- else }}
  .dockerconfigjson: ""
  {{- end }}