apiVersion: v1
kind: Secret
metadata:
  name: install-config-secret
  namespace: {{ .Values.cluster.namespace }}
type: Opaque
stringData:
  install-config.yaml: |
    apiVersion: v1
    baseDomain: {{ .Values.aws.baseDomain }}
    compute:
    - architecture: amd64
      hyperthreading: Enabled
      name: worker
      platform: {}
      replicas: 0
    controlPlane:
      architecture: amd64
      hyperthreading: Enabled
      name: master
      platform: {}
      replicas: 1
    metadata:
      name: {{ .Values.cluster.name }}
    networking:
      clusterNetwork:
      {{- toYaml .Values.network.clusterNetwork | nindent 10 }}
      machineNetwork:
      {{- toYaml .Values.network.machineNetwork | nindent 10 }}
      networkType: OpenShiftSDN
      serviceNetwork:
      {{- toYaml .Values.network.serviceNetwork | nindent 10 }}
    platform:
      aws:
        region: {{ .Values.aws.region }}
    publish: External
    pullSecret: {{ .Values.auth.pullSecret }}
    sshKey: {{ .Values.auth.sshPublicKey }}

