apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: {{ .Values.cluster.name }}-worker
  namespace: {{ .Values.cluster.namespace }}
spec:
  clusterDeploymentRef:
    name: {{ .Values.cluster.name }}
  name: worker
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: m5.xlarge
  replicas: 0