apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    env: development
    region: {{ .Values.aws.region }}
    name: {{ .Values.cluster.name }}
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: 'default'
    owner: {{ .Values.tags.owner }}
  name: {{ .Values.cluster.name }}
spec:
  hubAcceptsClient: true