apiVersion: v1
kind: Secret
metadata:
  # Leaving this name as-is since this install-config is specific to SNO
  name: single-node-cluster-install-config
  namespace: {{ .Values.cluster.namespace }}
type: Opaque
stringData:
  install-config.yaml: |
    apiVersion: v1
    metadata:
      name: {{ .Values.cluster.name }}
    baseDomain: {{ .Values.aws.baseDomain }}
    controlPlane:
      architecture: amd64
      hyperthreading: Enabled
      name: master
      replicas: 1
      platform:
        aws:
          rootVolume:
            iops: 4000
            size: 100
            type: io1
          type: m5.xlarge
    compute:
    - hyperthreading: Enabled
      architecture: amd64
      name: 'worker'
      replicas: 0
      platform:
        aws:
          rootVolume:
            iops: 2000
            size: 100
            type: io1
          type: m5.xlarge
    networking:
      networkType: OVNKubernetes
      clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      machineNetwork:
      - cidr: 10.0.0.0/16
      serviceNetwork:
      - 172.30.0.0/16
    platform:
      aws:
        region: {{ .Values.aws.region }}
    pullSecret: "" # skip, hive will inject based on it's secrets
    sshKey: |-
      {{ .Values.auth.sshPublicKey | b64dec }}
