apiVersion: v1
kind: Secret
metadata:
  # Leaving this name as-is since this install-config is specific to SNO
  name: single-node-cluster-install-config
  namespace: {{ .Values.cluster.namespace }}
type: Opaque
stringData:
  install-config.yaml: |
    apiVersion: v1
    baseDomain: {{ .Values.aws.baseDomain }}
    compute:
    - architecture: amd64
      hyperthreading: Enabled
      name: worker
      platform: {}
      replicas: 0
      platform:
        aws:
          rootVolume:
            iops: 2000
            size: 100
            type: io1
          type: m5.xlarge
    controlPlane:
      architecture: amd64
      hyperthreading: Enabled
      name: master
      platform: {}
      replicas: 1
      platform:
        aws:
          zones:
          - {{ .Values.aws.region }}a
          rootVolume:
            iops: 4000
            size: 100
            type: io1
          type: m5.xlarge
    metadata:
      name: {{ .Values.cluster.name }}
    networking:
      clusterNetwork:
      {{- toYaml .Values.network.clusterNetwork | nindent 10 }}
      machineNetwork:
      {{- toYaml .Values.network.machineNetwork | nindent 10 }}
      networkType: OVNKubernetes
      serviceNetwork:
      {{- toYaml .Values.network.serviceNetwork | nindent 10 }}
    platform:
      aws:
        region: {{ .Values.aws.region }}
    publish: External
    # pullSecret: {{ .Values.auth.pullSecret }}
    pullSecret: "" # skip, hive will inject based on it's secrets
    sshKey: {{ .Values.auth.sshPublicKey }}

